apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angularapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/el-boukhari/angular-gitops-part.git
    targetRevision: HEAD
    path: K8sFiles
  destination:
    server: https://kubernetes.default.svc
    namespace: angular-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

