apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angularfrontend
  template:
    metadata:
      labels:
        app: angularfrontend
    spec:
      containers:
        - name: angular
          image: nginx:latest
          ports:
            - containerPort: 80
